#!/bin/bash
# result=()
while read line && [ "$line" != "" ]
do
    result=("${result[@]}" $line)
    # echo $result
done
echo "$result $result $result"

# while read line && [ "$line" != "" ]
# do
#     my_array=("${my_array[@]}" $line)
# done
#  my_array=("${my_array[@]}" "${my_array[@]}" "${my_array[@]}")
# echo ${my_array[@]}