#!/bin/bash
read num
sum=0
for ((i = 0 ; i < $num ; i++)); do
  read input
  sum=$((input + sum))
  #echo $sum
done

printf %.3f $(echo "$sum/$num" | bc -l)
echo -e "\r"



xxx=$( grep 'twitter.com' file)


#echo $xxx | grep -aob '/' | grep -oE '[0-9]+'
test=$( echo $xxx | grep -aob '/' | grep -oE '[0-9]+' )

echo $test

myvar='abc'
printf '%s\n' "$myvar" | cut -c2